version: '4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongo_user:mongo_password@mongodb:27017
